# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Orbs provide reusable configurations.
orbs:
  node: circleci/node@5.2

# Define the jobs
jobs:
  test:
    # Usa la orb para el entorno de Node.js, pero definiendo comandos personalizados.
    docker:
      - image: cimg/node:16.10 # Define la versión de Node.js a utilizar
    steps:
      - checkout
      - node/install-packages: # Instala dependencias usando npm o yarn
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm test -- --passWithNoTests

# Define workflows
workflows:
  sample_workflow:
    jobs:
      - test
